### ISSUE TITLE
figure out why merlin's not working for some people

### ISSUE THREAD

**Issue by jaredly** [jaredly/ohai#1] opened 2017-06-19 14:48 UTC

**Comment by bobbypriam** [comment] 2017-06-23 14:32
Hi Jared, have you managed to solve this?

I've tried adding a jbuild at my root with just a `(jbuild_version 1)` line but it doesn't generate the `.merlin` file, which I think makes sense since you would need to define either `library` or `executable` stanza along with `libraries`. However, I can't wrap around my head on how the jbuild file on the root should look like or if it is possible at all. Manually creating `.merlin` would not be feasible since we would lose jbuilder's capability of automatically locating dependencies.

So far the way I found to make merlin work properly is to open the subdirectories as the root (e.g. `code lib` or `code test` if you're using VSCode). But then again, it feels really awkward... not to mention VSCode [doesn't support opening multiple directories in one window yet](https://github.com/Microsoft/vscode/issues/396), and you end up with at least two windows for `lib` and `test`, which is sad because [vscode-reasonml](https://github.com/freebroccolo/vscode-reasonml) is by far the best OCaml plugin I ever encountered that works out-of-the-box.

(Do note that I'm pretty much still an OCaml—and therefore merlin and jbuilder—noob so I might be missing something basic.)

**Comment by jaredly** [comment] 2017-06-23 15:35
The .merlin file should be created once you build -- if you add the `jbuild` file and then run `make` does the .merlin file get created?

**Comment by bobbypriam** [comment] 2017-06-23 15:54
Yes, I have run `make` after creating the jbuild file and no, it doesn't seem that the .merlin file is generated. I even tried cleaning the build files (removing `_build` and `(bin|lib|test)/.merlin`) and running `make` again, the removed files got built but still no .merlin on root. My guess is it's related to the content of the jbuild file, which currently only contains `(jbuild_version 1)`.

**Comment by jaredly** [comment] 2017-06-23 21:35
hmmm actually I've got merlin working in vscode, without any `.merlin` at the root. `lib` etc. have .merlin files, and I get type hinting and everything

**Comment by bobbypriam** [comment] 2017-06-24 00:53
Oh, that's weird. Which plugin are you using?

**Comment by bobbypriam** [comment] 2017-06-24 02:37
@jaredly It seems that you're right, the issue is most likely on the VSCode plugin that I use ([vscode-reasonml](https://github.com/freebroccolo/vscode-reasonml) on master branch which provides OCaml support. There's already [an issue opened](https://github.com/freebroccolo/vscode-reasonml/issues/76)). I'm guessing you're using a different plugin? Using Atom + ocaml-merlin, vim, and emacs works fine.

I think you can close this issue. Thanks for your support and sorry for the false alarm!

**Closed as completed** 2017-06-28 15:20 UTC
